modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="navalarmamentsrebooted"
version="${file.jarVersion}"
displayName="Navalarmamentsrebooted"
authors="AquTheSeal, Sajevius"
description='''
A fully-coded remake of one of @Aqu's MCreator mods which was Naval Armaments! This mod has a bunch of balanced weapons with their own variety with Chaos Awakens support.
'''

[[dependencies.navalarmamentsrebooted]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.navalarmamentsrebooted]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"

[[dependencies.navalarmamentsrebooted]]
modId="chaosawakens"
mandatory=true
versionRange="[0.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.navalarmamentsrebooted]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"